language: php

matrix:
  fast_finish: true
  include:
#  - php: 7.0
#    env: TYPO3_VERSION=^8
#  - php: 7.1
#    env: TYPO3_VERSION=^8
  - php: 7.2
    env: TYPO3_VERSION=^9

sudo: false

cache:
  directories:
  - $HOME/.composer/cache

before_install:
- composer self-update
- composer --version

before_script:
- phpenv config-rm xdebug.ini
- composer require typo3/cms-core=$TYPO3_VERSION
- git checkout composer.json
- export TYPO3_PATH_WEB=$PWD/Build/web

script:
- vendor/bin/phpunit -c vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/