<?php

namespace Brotkrueml\Sdbreadcrumb\ViewHelpers;

use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3Fluid\Fluid\Core\Rendering\RenderingContextInterface;
use TYPO3Fluid\Fluid\Core\ViewHelper;

/**
 * ViewHelper to render breadcrumb markup as json-ld
 */
class BreadcrumbMarkupViewHelper extends ViewHelper\AbstractViewHelper
{
    protected $escapeOutput = false;

    public function initializeArguments()
    {
        parent::initializeArguments();

        $this->registerArgument(
            'breadcrumb',
            'array',
            'The breadcrumb generated by the MenuProcessor or an equivalent data structure',
            true);

        $this->registerArgument(
            'stripFirstItem',
            'bool',
            'Strips off the first item of the breadcrumb, normally the start page',
            false,
            true
        );
    }

    static public function renderStatic(
        array $arguments,
        \Closure $renderChildrenClosure,
        RenderingContextInterface $renderingContext
    ) {
        $breadcrumb = $arguments['breadcrumb'];

        if ($arguments['stripFirstItem']) {
            $breadcrumb = array_slice($breadcrumb, 1);
        }

        if (!count($breadcrumb)) {
            return '';
        }

        $siteUrl = GeneralUtility::getIndpEnv('TYPO3_SITE_URL');
        if ($breadcrumb[0]['link'][0] === '/') {
            $siteUrl = rtrim($siteUrl, '/');
        }

        $markup = [
            '@context' => 'http://schema.org',
            '@type' => 'BreadcrumbList',
            'itemListElement' => [],
        ];

        foreach ($breadcrumb as $index => $item) {
            $markup['itemListElement'][] = [
                '@type' => 'ListItem',
                'position' => $index + 1,
                'item' => [
                    '@id' =>  $siteUrl . $item['link'],
                    'name' => $item['title'],
                ],
            ];
        }

        return '<script type="application/ld+json">'
            . json_encode($markup, JSON_UNESCAPED_SLASHES)
            . '</script>';
    }
}